#!/usr/bin/env python3
"""Runs production hook code against narrow Android/Xposed fakes. Not a device or HAL test."""
import os, pathlib, subprocess, tempfile
ROOT=pathlib.Path(__file__).resolve().parents[1]
SOURCES={
 'com/android/bluetooth/hfpclient/HeadsetClientService.java': """package com.android.bluetooth.hfpclient;import java.util.*;import android.bluetooth.BluetoothDevice;public class HeadsetClientService {public static final HeadsetClientService instance=new HeadsetClientService();public static int dialed,answered,ended;public static List<BluetoothDevice> devices=new ArrayList<>();static {devices.add(new BluetoothDevice());}public static HeadsetClientService getHeadsetClientService(){return instance;}public List<BluetoothDevice> getConnectedDevices(){return devices;}public Object dial(BluetoothDevice d,String number){dialed++;return new Object();}public boolean acceptCall(BluetoothDevice d,int flag){if(flag!=0)throw new AssertionError();answered++;return true;}public boolean terminateCall(BluetoothDevice d,UUID id){if(id!=null)throw new AssertionError();ended++;return true;}}""",
'android/util/Log.java': '''package android.util; public class Log {public static java.util.List<String> lines=new java.util.ArrayList<>(); public static int i(String t,String s){lines.add(s);return 0;} public static int e(String t,String s){lines.add(s);return 0;}}''',
'android/os/Process.java': 'package android.os; public class Process {public static int myPid(){return 123;}}',
'android/os/SystemClock.java': 'package android.os; public class SystemClock {public static long elapsedRealtime(){return 42;}}',
'android/os/SystemProperties.java': '''package android.os; public class SystemProperties {public static String mode="observe";public static String get(String k,String d){return k.endsWith(".mode")?mode:d;}}''',
'android/telecom/DisconnectCause.java': 'package android.telecom; public class DisconnectCause {public static final int CANCELED=4;public DisconnectCause(int x){}}',
'android/telecom/Connection.java': '''package android.telecom; public class Connection {public boolean voip;public static Connection createFailedConnection(DisconnectCause c){return new Connection();}public void setAudioModeIsVoip(boolean b){voip=b;}}''',
'android/telecom/PhoneAccountHandle.java': 'package android.telecom; public class PhoneAccountHandle {}',
'android/telecom/ConnectionRequest.java': 'package android.telecom; public class ConnectionRequest {}',
'android/bluetooth/BluetoothDevice.java': 'package android.bluetooth;public class BluetoothDevice {}',
'android/bluetooth/BluetoothHeadsetClientCall.java': '''package android.bluetooth;public class BluetoothHeadsetClientCall {public int state;public String key="call1";public Object getUUID(){return key;}public int getState(){return state;}}''',
'android/media/AudioSystem.java': '''package android.media;public class AudioSystem {public static java.util.Set<Integer> ports=new java.util.HashSet<>();public static java.util.List<String> params=new java.util.ArrayList<>();public static String wbs="bt_wbs=off",btSco="BT_SCO=off";public static int writes,failParamStatus,prematureModeWrites;public static boolean throwParam,nativeRouteReturned; public static int setParameters(String s){writes++;params.add(s);if((s.equals("bt_wbs=on")||s.equals("BT_SCO=on"))&&!nativeRouteReturned)prematureModeWrites++;if(throwParam)throw new RuntimeException("HAL unavailable");if(s.startsWith("bt_wbs="))wbs=s;if(s.startsWith("BT_SCO="))btSco=s;return failParamStatus;} public static String getParameters(String k){return wbs;}public static int getDeviceConnectionState(int t,String a){return ports.contains(t)?1:0;}public static int setDeviceConnectionState(int t,int s,String a,String n,int f){if(s==1)ports.add(t);else ports.remove(t);return 0;}}''',
'android/media/AudioPatch.java': 'package android.media;public class AudioPatch {public String path;public AudioPatch(String p){path=p;}}',
'android/media/AudioPortConfig.java': 'package android.media;public class AudioPortConfig {public int type;public AudioPortConfig(int t){type=t;}}',
'android/media/AudioManager.java': '''package android.media;public class AudioManager {public static int mode,modeSets,foreignMode;public static boolean ignoreMode,throwRelease;public int getMode(){return mode;}public void setMode(int value){modeSets++;if(value==0&&throwRelease)throw new RuntimeException("release denied");if(!ignoreMode)mode=value==0?foreignMode:value;}public static final int MODE_NORMAL=0,MODE_IN_COMMUNICATION=3;public static java.util.List<String> created=new java.util.ArrayList<>();public static java.util.List<String> released=new java.util.ArrayList<>();public static boolean failRx;public static class Port {int type;public Port(int t){type=t;}public int type(){return type;}public String address(){return "AA";}public AudioPortConfig buildConfig(int a,int b,int c,Object d){return new AudioPortConfig(type);}}public static int listAudioDevicePorts(java.util.List<Object> p){for(int t:new int[]{0x80000008,0x20,2,0x80000004})p.add(new Port(t));return 0;}public static int createAudioPatch(AudioPatch[] p,AudioPortConfig[] s,AudioPortConfig[] d){String path=s[0].type+":"+d[0].type;created.add(path);p[0]=new AudioPatch(path);return 0;}public static int releaseAudioPatch(AudioPatch p){if(failRx&&p.path.endsWith(":2"))return -1;released.add(p.path);return 0;}}''',
'com/android/bluetooth/hfpclient/HeadsetClientStateMachine.java': '''package com.android.bluetooth.hfpclient;public class HeadsetClientStateMachine {public android.media.AudioManager mAudioManager=new android.media.AudioManager();public boolean mAudioWbs=true;public Object mCurrentDevice=new Device();public static class Device{public String getAddress(){return "AA";}}}''',
'com/android/bluetooth/hfpclient/connserv/HfpClientConnectionService.java': 'package com.android.bluetooth.hfpclient.connserv;public class HfpClientConnectionService {}',
'com/android/bluetooth/hfpclient/connserv/HfpClientDeviceBlock.java': 'package com.android.bluetooth.hfpclient.connserv;public class HfpClientDeviceBlock {public java.util.Map<Object,Object> mConnections=new java.util.HashMap<>();}',
'de/robv/android/xposed/IXposedHookLoadPackage.java': 'package de.robv.android.xposed;public interface IXposedHookLoadPackage {void handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage.LoadPackageParam p);}',
'de/robv/android/xposed/callbacks/XC_LoadPackage.java': 'package de.robv.android.xposed.callbacks;public class XC_LoadPackage {public static class LoadPackageParam{public String packageName;public ClassLoader classLoader;}}',
'de/robv/android/xposed/XC_MethodHook.java': '''package de.robv.android.xposed;public class XC_MethodHook {protected void beforeHookedMethod(MethodHookParam p)throws Throwable{} protected void afterHookedMethod(MethodHookParam p)throws Throwable{} public void before(MethodHookParam p)throws Throwable{beforeHookedMethod(p);}public void after(MethodHookParam p)throws Throwable{afterHookedMethod(p);}public static class Unhook{}public static class MethodHookParam {public Object thisObject;public Object[] args;public Object result;public boolean returned;public Throwable error;public java.util.Map<String,Object> extra=new java.util.HashMap<>();public Object getResult(){return result;}public void setResult(Object r){result=r;returned=true;}public boolean hasThrowable(){return error!=null;}public Throwable getThrowable(){return error;}public Object getObjectExtra(String k){return extra.get(k);}public void setObjectExtra(String k,Object v){extra.put(k,v);}}}''',
'de/robv/android/xposed/XposedHelpers.java': '''package de.robv.android.xposed;public class XposedHelpers {public static String missing="";public static java.util.Map<String,XC_MethodHook> hooks=new java.util.HashMap<>();public static Class<?> findClass(String n,ClassLoader l){try{return Class.forName(n);}catch(Exception e){throw new RuntimeException(e);}}public static XC_MethodHook.Unhook findAndHookMethod(Class<?> c,String n,Object...a){if(n.equals(missing))throw new RuntimeException("missing");hooks.put(n,(XC_MethodHook)a[a.length-1]);return new XC_MethodHook.Unhook();}public static Object getObjectField(Object o,String n){try{return o.getClass().getField(n).get(o);}catch(Exception e){throw new RuntimeException(e);}}public static Object callMethod(Object o,String n,Object...a){return invoke(o.getClass(),o,n,a);}public static Object callStaticMethod(Class<?> c,String n,Object...a){return invoke(c,null,n,a);}static Object invoke(Class<?> c,Object o,String n,Object[]a){for(java.lang.reflect.Method m:c.getMethods())if(m.getName().equals(n)&&m.getParameterCount()==a.length)try{return m.invoke(o,a);}catch(Exception e){throw new RuntimeException(e);}throw new RuntimeException(n);}}''',
'com/hfpvoipfix/HookSafetyTest.java': '''package com.hfpvoipfix;
import de.robv.android.xposed.*;import de.robv.android.xposed.callbacks.*;import android.media.*;import android.os.SystemProperties;import android.bluetooth.BluetoothHeadsetClientCall;import com.android.bluetooth.hfpclient.*;import com.android.bluetooth.hfpclient.connserv.*;
public class HookSafetyTest {
 static HeadsetClientStateMachine sm=new HeadsetClientStateMachine();static BluetoothHeadsetClientCall call=new BluetoothHeadsetClientCall();static int checks;
 static void check(boolean b,String message){checks++;if(!b)throw new AssertionError(message);}
 static XC_MethodHook.MethodHookParam invoke(String method,Object obj,Object result,Object...args)throws Throwable{XC_MethodHook h=XposedHelpers.hooks.get(method);XC_MethodHook.MethodHookParam p=new XC_MethodHook.MethodHookParam();p.thisObject=obj;p.args=args;p.result=result;h.before(p);h.after(p);return p;}
 static void state(int s)throws Throwable{call.state=s;invoke("sendCallChangedIntent",sm,null,call);}
 static void route(boolean b)throws Throwable{XC_MethodHook h=XposedHelpers.hooks.get("routeHfpAudio");XC_MethodHook.MethodHookParam p=new XC_MethodHook.MethodHookParam();p.thisObject=sm;p.args=new Object[]{b};AudioSystem.nativeRouteReturned=false;h.before(p);AudioSystem.nativeRouteReturned=true;h.after(p);}
 static void begin(String m)throws Throwable{SystemProperties.mode=m;state(0);}
 static void end()throws Throwable{state(7);route(false);}
 public static void main(String[]args)throws Throwable{
  if(args.length>0)XposedHelpers.missing=args[0].equals("disconnect")?"broadcastConnectionState":"sendCallChangedIntent";
  XC_LoadPackage.LoadPackageParam p=new XC_LoadPackage.LoadPackageParam();p.packageName="com.android.bluetooth";p.classLoader=HookSafetyTest.class.getClassLoader();new HfpVoipFix().handleLoadPackage(p);
  if(args.length>0){SystemProperties.mode=args[0].equals("disconnect")?"bypass_comm":"bridge";route(true);check(AudioSystem.ports.isEmpty()&&AudioManager.created.isEmpty()&&AudioManager.modeSets==0,"Missing lifecycle must fail closed");System.out.println("PASS missing lifecycle fail closed");return;}
  begin("voip");android.telecom.Connection c=new android.telecom.Connection();invoke("onCreateIncomingConnection",null,c,null,null);route(true);check(c.voip,"Early VoIP");check(AudioSystem.writes==0&&AudioSystem.ports.isEmpty(),"A must not touch codec/ports");end();
  begin("wbs");route(true);check(AudioSystem.wbs.equals("bt_wbs=on"),"B WBS applied");end();check(AudioSystem.wbs.equals("bt_wbs=off"),"WBS restored");
  sm.mAudioWbs=false;int writes=AudioSystem.writes;begin("wbs");route(true);check(AudioSystem.writes==writes,"B cannot force WBS after narrow negotiation");end();
  AudioSystem.wbs="";begin("codec");route(true);check(AudioSystem.writes==writes,"E must skip unknown original HAL value");end();AudioSystem.wbs="bt_wbs=on";
  begin("codec");route(true);check(AudioSystem.wbs.equals("bt_wbs=off"),"E follows narrow negotiation");end();check(AudioSystem.wbs.equals("bt_wbs=on"),"E restores exact previous value");
  begin("endpoints");route(true);check(AudioSystem.ports.size()==2,"C registers SCO ports");SystemProperties.mode="observe";route(false);route(true);check(AudioSystem.ports.size()==2,"Strategy latched across SCO gap within a call");end();check(AudioSystem.ports.isEmpty(),"Owned ports released");
  begin("observe");route(true);check(AudioSystem.ports.isEmpty(),"Observe takes effect next call");end();
  AudioSystem.ports.add(0x20);begin("endpoints");route(true);end();check(AudioSystem.ports.contains(0x20),"Preexisting SCO port preserved");AudioSystem.ports.clear();
  int created=AudioManager.created.size();begin("rx");route(true);check(AudioManager.created.size()==created+1&&AudioManager.created.get(created).endsWith(":2"),"G RX only");route(true);check(AudioManager.created.size()==created+1,"Repeated route must not recreate patch");end();
  created=AudioManager.created.size();begin("tx");route(true);check(AudioManager.created.size()==created+1&&AudioManager.created.get(created).endsWith(":32"),"H TX only");end();
  created=AudioManager.created.size();begin("bridge");route(true);check(AudioManager.created.size()==created+2,"I both directions");AudioManager.failRx=true;end();check(!AudioSystem.ports.isEmpty(),"Failed release retains cleanup ownership");begin("bridge");route(true);check(AudioManager.created.size()==created+2,"Failed cleanup forbids new bridge");AudioManager.failRx=false;end();check(AudioSystem.ports.isEmpty(),"Later successful cleanup releases owned ports");
  HfpClientDeviceBlock block=new HfpClientDeviceBlock();begin("bypass");check(invoke("handleCall",block,null,call).returned,"D prevents only HFP connserv registration");check(invoke("onCreateOutgoingConnection",null,null,null,null).returned,"D refuses local Telecom dialing");end();
  block.mConnections.put("existing",new Object());begin("bypass");check(!invoke("handleCall",block,null,call).returned,"D unavailable with preexisting Telecom connections");end();
  block.mConnections.clear();AudioManager.mode=0;int modeSets=AudioManager.modeSets;
  begin("bypass_comm");route(true);check(AudioManager.modeSets==modeSets,"D1 waits for confirmed bypass");
  invoke("handleCall",block,null,call);check(AudioManager.mode==3,"D1 activates communication after late bypass confirmation");
  route(true);check(AudioManager.modeSets==modeSets+1,"D1 duplicate route does not re-request mode");
  route(false);check(AudioManager.mode==3,"D1 mode held across SCO gap while call active");route(true);end();check(AudioManager.mode==0,"D1 restores mode after both call and SCO end");
  begin("bypass_comm");invoke("handleCall",block,null,call);route(true);state(7);check(AudioManager.mode==3,"D1 waits for route teardown after call termination");route(false);check(AudioManager.mode==0,"D1 call-first cleanup");
  AudioManager.mode=2;modeSets=AudioManager.modeSets;begin("bypass_comm");invoke("handleCall",block,null,call);route(true);check(AudioManager.mode==2&&AudioManager.modeSets==modeSets,"D1 refuses active SIM audio mode");end();AudioManager.mode=0;
  AudioManager.ignoreMode=true;begin("bypass_comm");invoke("handleCall",block,null,call);route(true);check(AudioManager.mode==0,"D1 does not claim requested mode effective after ignored setMode");end();AudioManager.ignoreMode=false;
  begin("bypass_comm");invoke("handleCall",block,null,call);route(true);invoke("broadcastConnectionState",sm,null,null,0,2);check(AudioManager.mode==0,"D1 restores on Bluetooth profile disconnect without call-end event");
  begin("bypass_comm");invoke("handleCall",block,null,call);route(true);AudioManager.foreignMode=2;AudioManager.mode=2;end();check(AudioManager.mode==2,"D1 release preserves later SIM owner's request");AudioManager.foreignMode=0;AudioManager.mode=0;
  begin("bypass_comm");invoke("handleCall",block,null,call);route(true);AudioManager.throwRelease=true;end();check(AudioManager.mode==3,"Failed mode cleanup remains visible");modeSets=AudioManager.modeSets;begin("bypass_comm");route(true);check(AudioManager.modeSets==modeSets,"Failed mode cleanup prevents new request");AudioManager.throwRelease=false;end();check(AudioManager.mode==0,"Pending cleanup can release after transient error");
  writes=AudioSystem.writes;created=AudioManager.created.size();modeSets=AudioManager.modeSets;AudioSystem.params.clear();AudioSystem.prematureModeWrites=0;AudioSystem.wbs="bt_wbs=off";sm.mAudioWbs=true;
  begin("soft_rx");check(invoke("handleCall",block,null,call).returned,"D2 suppresses HFP Telecom registration");route(true);
  check(AudioSystem.ports.size()==1&&AudioSystem.ports.contains(0x80000008),"D2 exposes only SCO input");check(AudioManager.created.size()==created,"D2 never creates AudioPatch");check(AudioManager.modeSets==modeSets,"D2 does not change Android communication mode");check(AudioSystem.params.equals(java.util.Arrays.asList("BT_SCO=on","bt_wbs=on"))&&AudioSystem.btSco.equals("BT_SCO=on"),"D2 enables the MediaTek SCO path and WBS only after native HFP route");check(AudioSystem.prematureModeWrites==0,"D2 never writes MediaTek mode before native route returns");
  SystemProperties.mode="bridge";route(true);check(AudioManager.created.size()==created,"D2 remains latched during call");end();check(AudioSystem.ports.isEmpty(),"D2 releases owned ports");check(AudioSystem.params.equals(java.util.Arrays.asList("BT_SCO=on","bt_wbs=on","bt_wbs=off","BT_SCO=off")),"D2 restores the MediaTek WBS and SCO idle state after SCO");
  AudioSystem.wbs="";AudioSystem.params.clear();begin("soft_rx");route(true);check(AudioSystem.params.equals(java.util.Arrays.asList("BT_SCO=on","bt_wbs=on")),"D2 proceeds with the documented idle baseline when HAL WBS getter is unreadable");end();check(AudioSystem.params.equals(java.util.Arrays.asList("BT_SCO=on","bt_wbs=on","bt_wbs=off","BT_SCO=off"))&&AudioSystem.wbs.equals("bt_wbs=off")&&AudioSystem.btSco.equals("BT_SCO=off"),"D2 restores the documented WBS and SCO idle baselines after unreadable WBS getter");
  AudioSystem.wbs="bt_wbs=off";
  sm.mAudioWbs=false;AudioSystem.params.clear();begin("soft_rx");route(true);check(AudioSystem.params.isEmpty(),"D2 leaves MediaTek mode unchanged for narrowband calls");end();
  sm.mAudioWbs=true;AudioSystem.params.clear();AudioSystem.failParamStatus=-38;begin("soft_rx");route(true);check(AudioSystem.ports.isEmpty()&&AudioSystem.params.equals(java.util.Arrays.asList("BT_SCO=on","bt_wbs=off")),"D2 fails closed when MediaTek SCO state request is rejected and restores the WBS baseline");end();AudioSystem.failParamStatus=0;end();
  AudioSystem.params.clear();AudioSystem.throwParam=true;begin("soft_rx");route(true);check(AudioSystem.ports.isEmpty(),"D2 fails closed if MediaTek request throws");end();AudioSystem.throwParam=false;end();
  created=AudioManager.created.size();AudioSystem.params.clear();begin("soft_tx");route(true);
  check(AudioSystem.ports.size()==1&&AudioSystem.ports.contains(0x20)&&!AudioSystem.ports.contains(0x80000008),"D3 exposes only SCO output for microphone TX");
  check(AudioManager.created.size()==created,"D3 never creates AudioPatch");
  check(AudioSystem.params.equals(java.util.Arrays.asList("BT_SCO=on","bt_wbs=on")),"D3 requests the same negotiated MediaTek SCO path only after native HFP routing");
  end();check(AudioSystem.ports.isEmpty()&&AudioSystem.params.equals(java.util.Arrays.asList("BT_SCO=on","bt_wbs=on","bt_wbs=off","BT_SCO=off")),"D3 releases SCO output and restores MediaTek idle settings");
  java.lang.reflect.Method command=HfpVoipFix.class.getDeclaredMethod("executeControl",String.class);command.setAccessible(true);
  SystemProperties.mode="observe";command.invoke(null,"a1:dial:666");check(com.android.bluetooth.hfpclient.HeadsetClientService.dialed==0,"Controls refuse non-bypass mode");
  SystemProperties.mode="soft_rx";command.invoke(null,"a2:dial:666");check(com.android.bluetooth.hfpclient.HeadsetClientService.dialed==1,"Redmi command queues HFP dial");command.invoke(null,"a2:dial:666");check(com.android.bluetooth.hfpclient.HeadsetClientService.dialed==1,"Repeated command token never redials");
  begin("soft_rx");command.invoke(null,"a3:dial:666");check(com.android.bluetooth.hfpclient.HeadsetClientService.dialed==1,"Controls refuse second call");command.invoke(null,"a4:answer:-");command.invoke(null,"a5:hangup:-");check(com.android.bluetooth.hfpclient.HeadsetClientService.answered==1&&com.android.bluetooth.hfpclient.HeadsetClientService.ended==1,"Answer and hangup target remote HFP service");end();
  com.android.bluetooth.hfpclient.HeadsetClientService.devices.add(new android.bluetooth.BluetoothDevice());command.invoke(null,"a6:dial:666");check(com.android.bluetooth.hfpclient.HeadsetClientService.dialed==1,"Multiple HFP devices refused");
  String line="10-09 11:13:51.285  1889  2443 D AudioBTCVSDControl: BT_SCO_RX_Start(+) BTmode=0";check(Privacy.clean(line).equals(line),"System timestamps PID TID preserved");
  String numeric="sample_rate=16000 mask=0x80000008 ms=1791536801851 handle=123456789";check(Privacy.clean(numeric).equals(numeric),"Unlabelled technical values preserved");
  String multi="10-09 11:12:13.123  12  34 I Hfp: number=0612345678, rate=16000\\n10-09 11:12:14.000  12  34 I Hfp: samples=48000";check(Privacy.clean(multi).contains("samples=48000")&&!Privacy.clean(multi).contains("0612345678"),"Payload redaction leaves following line intact");
  String safe=Privacy.clean("number=0612345678, addr=AA:BB:CC:DD:EE:FF tel:+33612345678");check(!safe.contains("0612345678")&&!safe.contains("AA:BB"),"Phone and MAC redacted");String evt="HfpVoipFix LAB CALL id=1 state=7 mode=rx ms=1791500000000";check(Privacy.clean(evt).equals(evt),"Correlation timestamp preserved");
  System.out.println("PASS "+checks+" safety assertions; not a HAL/Android device test");
 }
}'''
}
with tempfile.TemporaryDirectory(dir=ROOT/'tests') as d:
 d=pathlib.Path(d); src=d/'src';out=d/'classes';out.mkdir()
 for name,s in SOURCES.items():
  p=src/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s)
 files=[str(p) for p in src.rglob('*.java')]+[str(ROOT/'app/src/main/java/com/hfpvoipfix'/n) for n in ('HfpVoipFix.java','LabModes.java','Privacy.java','CallCommand.java')]
 java=pathlib.Path(os.environ['JAVA_HOME'])/'bin'
 subprocess.run([str(java/'javac'),'-encoding','UTF-8','-d',str(out),*files],check=True)
 for args in ([],['missing'],['disconnect']):subprocess.run([str(java/'java'),'-cp',str(out),'com.hfpvoipfix.HookSafetyTest',*args],check=True)
