YªçŠx-®éÜj×¢ëiºÚ+Š§j[h‘éÜ¢éíó6N‹Z–‹­¦ëeŠw¬ÕÁ…­…”½´¹¡™ÁÙ½¥Á™¥àì)¥µÁ½ÉÐ…¹‘É½¥¹…ÁÀ¸¨ì)¥µÁ½ÉÐ…¹‘É½¥¹½Ì¸¨ì)¥µÁ½ÉÐ…¹‘É½¥¹½¹Ñ•¹Ð¸¨ì)¥µÁ½ÉÐ…¹‘É½¥¹Ý¥‘•Ð¸¨ì)¥µÁ½ÉÐ©…Ù„¹¥¼¸¨ì)¥µÁ½ÉÐ©…Ù„¹¹¥¼¹¡…ÉÍ•Ð¹MÑ…¹‘…É‘¡…ÉÍ•ÑÌì)¥µÁ½ÉÐ©…Ù„¹¹¥¼¹™¥±”¹¥±•Ìì)¥µÁ½ÉÐ©…Ù„¹ÕÑ¥°¹½¹ÕÉÉ•¹Ð¸¨ì()ÁÕ‰±¥Œ™¥¹…°±…ÍÌ5½‘•Ñ¥Ù¥Ñä•áÑ•¹‘ÌÑ¥Ù¥Ñäì(€€€ÁÉ¥Ù…Ñ”™¥¹…°á•ÕÑ½ÉM•ÉÙ¥”Ý½É¬õá•ÕÑ½ÉÌ¹¹•ÝM¥¹±•Q¡É•…‘á•ÕÑ½È ¤ì(€€€ÁÉ¥Ù…Ñ”™¥¹…°!…¹‘±•ÈÕ¤õ¹•Ü!…¹‘±•È¡1½½Á•È¹•Ñ5…¥¹1½½Á•È ¤¤ì(€€€ÁÉ¥Ù…Ñ”Q•áÑY¥•ÜÍÑ…ÑÕÌ±‘•Ñ…¥±Ì±¹½Ñ¥”ì(€€€ÁÉ¥Ù…Ñ”	ÕÑÑ½¸…ÁÁ±ä±ÍÑ…ÉÐ±ÍÑ½À±Í¹…À±Í¡…É”±É…Ñ”±¥¹ÍÁ•Ð±™¥ÉµÝ…É”±™¥ÉµÝ…É•M¡…É”±™¥ÉµÝ…É•%¹ÍÁ•Ðì(€€€ÁÉ¥Ù…Ñ”Q•áÑY¥•Ü™¥ÉµÝ…É•MÑ…ÑÕÌ±ÉáMÑ…ÑÕÌ±ÑÉ…¹ÍÁ½ÉÑMÑ…ÑÕÌì(€€€ÁÉ¥Ù…Ñ”	ÕÑÑ½¸ÉáÉ´±ÉáMÑ½À±ÁÉ½‰•	ÕÑÑ½¸ì(€€€ÁÉ¥Ù…Ñ”MÁ¥¹¹•Èµ½‘•Ì±…‘Ù…¹•‘5½‘•Ìì(€€€ÁÉ¥Ù…Ñ”‘¥ÑQ•áÐÁ¡½¹•9Õµ‰•Èì(€€€ÁÉ¥Ù…Ñ”¡•­	½àÉ¥Í¬ì(€€€ÁÉ¥Ù…Ñ”‰½½±•…¸Ù¥Í¥‰±”±Ý½É­¥¹œì(€€€ÁÉ¥Ù…Ñ”MÑÉ¥¹œÉ•ÅÕ•ÍÑ•ô‰¹½¸Û¥É¥™§¤ˆì(€€€ÁÉ¥Ù…Ñ”ÍÑ…Ñ¥Œ™¥¹…°MÑÉ¥¹mtAI%5Ie}%Lõì‰½‰Í•ÉÙ”ˆ°‰Í½™Ñ}Éàˆ°‰Í½™Ñ}Ñà‰ôì(€€€ÁÉ¥Ù…Ñ”ÍÑ…Ñ¥Œ™¥¹…°MÑÉ¥¹mtAI%5Ie}95LõìˆÀƒ
ÜS¥³¥Á¡½¹”¹‘É½¥ˆ°‰Èƒ
ÜK¥•ÁÑ¥½¸Ù…±¥“¥”ˆ°‰Ìƒ
ÜÍÍ…¤µ¥É¼‰ôì(€€€ÁÉ¥Ù…Ñ”ÍÑ…Ñ¥Œ™¥¹…°MÑÉ¥¹mtY9}%Lõìˆˆ°‰Ù½¥Àˆ°‰Ý‰Ìˆ°‰•¹‘Á½¥¹ÑÌˆ°‰‰åÁ…ÍÌˆ°‰‰åÁ…ÍÍ}½µ´ˆ°‰½‘•Œˆ°‰Éàˆ°‰Ñàˆ°‰‰É¥‘”‰ôì(€€€ÁÉ¥Ù…Ñ”ÍÑ…Ñ¥Œ™¥¹…°MÑÉ¥¹mtIMU1QLõì‰9½¸ƒ¥Ù…±×¤ˆ°‰M¥±•¹”ˆ°‰	¥À½¹Ñ¥¹Ôˆ°‰I•Ñ½ÕÈµ¥É½Á¡½¹”ˆ°‰Y½¥àÉ—Õ”µ…¥Ì“¥™½É·¥”ˆ°‰Y½¥à±…¥É”ˆ°‰M½¸Õ¹¥ÅÕ•µ•¹Ð…Ô“¥‰ÕÐ½Ôƒ€±„™¥¸ˆ°‰ÕÑÉ”‰ôì(€€€ÁÉ¥Ù…Ñ”…¹‘É½¥¹½¹Ñ•¹Ð¹M¡…É•‘AÉ•™•É•¹•ÌÁÉ•™Ì ¥íÉ•ÑÕÉ¸•ÑM¡…É•‘AÉ•™•É•¹•Ì ‰…ÁÑÕÉ”ˆ°À¤íô(€€€ÁÉ¥Ù…Ñ”Ù½¥…Ñ¥½¸¡MÑÉ¥¹œÌ¥íÍÑ…ÉÑ½É•É½Õ¹‘M•ÉÙ¥”¡¹•Ü%¹Ñ•¹Ð¡Ñ¡¥Ì±…ÁÑÕÉ•M•ÉÙ¥”¹±…ÍÌ¤¹Í•ÑÑ¥½¸¡Ì¤¤íô(€€€ÁÉ¥Ù…Ñ”Ù½¥Ñ•áÐ¡1¥¹•…É1…å½ÕÐ°±MÑÉ¥¹œÌ±¥¹ÐÍ¥é”¥íQ•áÑY¥•ÜÐõ¹•ÜQ•áÑY¥•Ü¡Ñ¡¥Ì¤íÐ¹Í•ÑQ•áÐ¡Ì¤íÐ¹Í•ÑQ•áÑM¥é”¡Í¥é”¤íÐ¹Í•ÑA…‘‘¥¹œ À°ÄÈ°À°ÄÈ¤í°¹…‘‘Y¥•Ü¡Ð¤íô(€€€ÁÉ¥Ù…Ñ”	ÕÑÑ½¸‰ÕÑÑ½¸¡1¥¹•…É1…å½ÕÐ°±MÑÉ¥¹œÌ±IÕ¹¹…‰±”È¥í	ÕÑÑ½¸ˆõ¹•Ü	ÕÑÑ½¸¡Ñ¡¥Ì¤íˆ¹Í•ÑQ•áÐ¡Ì¤íˆ¹Í•Ñ±±…ÁÌ¡™…±Í”¤íˆ¹Í•Ñ=¹±¥­1¥ÍÑ•¹•È¡Ø´ùÈ¹ÉÕ¸ ¤¤í°¹…‘‘Y¥•Ü¡ˆ¤íÉ•ÑÕÉ¸ˆíô(€€€ÁÉ¥Ù…Ñ”Ù½¥Ñ½…ÍÐ¡MÑÉ¥¹œÌ¥í¹½Ñ¥”¹Í•ÑQ•áÐ¡Ì¤íô(€€€ÁÉ¥Ù…Ñ”MÑÉ¥¹œÍ•±•Ñ•‘5½‘” ¥í¥˜¡…‘Ù…¹•‘5½‘•Ì„õ¹Õ±°˜™…‘Ù…¹•‘5½‘•Ì¹•ÑM•±•Ñ•‘%Ñ•µA½Í¥Ñ¥½¸ ¤øÀ¥É•ÑÕÉ¸Y9}%Mm…‘Ù…¹•‘5½‘•Ì¹•ÑM•±•Ñ•‘%Ñ•µA½Í¥Ñ¥½¸ ¥tíÉ•ÑÕÉ¸AI%5Ie}%Mmµ½‘•Ì¹•ÑM•±•Ñ•‘%Ñ•µA½Í¥Ñ¥½¸ ¥tíô(€€€ÁÉ¥Ù…Ñ”Ù½¥Í¡½Ý5½‘” ¥í¥˜¡‘•Ñ…¥±Ìôõ¹Õ±±ññµ½‘•Ìôõ¹Õ±°¥É•ÑÕÉ¸íMÑÉ¥¹œ¥õÍ•±•Ñ•‘5½‘” ¤í‘•Ñ…¥±Ì¹Í•ÑQ•áÐ¡1…‰5½‘•Ì¹Q%1Mm1…‰5½‘•Ì¹¥¹‘•à¡¥¥t¬‰q¹5%U$€ÄÈ¸Ô€èË¥ÍÕ±Ñ…Ð“Še•ã¥ÕÑ¥½¸ƒ€Û¥É¥™¥•È‘…¹Ì±”É…ÁÁ½ÉÐ¸ˆ¤íÉ•™É•Í  ¤íô(€€€ÁÉ¥Ù…Ñ”Ù½¥Ñ…Í¬¡¡•­•‘Q…Í¬È¥í¥˜¡Ý½É­¥¹œ¥É•ÑÕÉ¸íÝ½É­¥¹œõÑÉÕ”íÉ•™É•Í  ¤íÝ½É¬¹•á•ÕÑ”  ¤´ùì(€€€€€€€ÑÉåíÈ¹ÉÕ¸ ¤íõ…Ñ ¡á•ÁÑ¥½¸”¥íÕ¤¹Á½ÍÐ  ¤´ùÑ½…ÍÐ ‰ÉÉ•ÕÈ€è€ˆ­”¹•Ñ5•ÍÍ…” ¤¤¤íô(€€€€€€€™¥¹…±±åíÕ¤¹Á½ÍÐ  ¤´ùíÝ½É­¥¹œõ™…±Í”íÉ•™É•Í  ¤íô¤íô(€€€ô¤íô(€€€ÁÉ¥Ù…Ñ”¥¹Ñ•É™…”¡•­•‘Q…Í­íÙ½¥ÉÕ¸ ¥Ñ¡É½ÝÌá•ÁÑ¥½¸íô(€€€=Ù•ÉÉ¥‘”ÁÕ‰±¥ŒÙ½¥½¹É•…Ñ”¡	Õ¹‘±”ˆ¥íÍÕÁ•È¹½¹É•…Ñ”¡ˆ¤ì(€€€€€€€MÉ½±±Y¥•ÜÍÉ½±°õ¹•ÜMÉ½±±Y¥•Ü¡Ñ¡¥Ì¤í1¥¹•…É1…å½ÕÐ°õ¹•Ü1¥¹•…É1…å½ÕÐ¡Ñ¡¥Ì¤í°¹Í•Ñ=É¥•¹Ñ…Ñ¥½¸ Ä¤í¥¹ÐÁ…ô¡¥¹Ð¤ Äà©•ÑI•Í½ÕÉ•Ì ¤¹•Ñ¥ÍÁ±…å5•ÑÉ¥Ì ¤¹‘•¹Í¥Ñä¤í°¹Í•ÑA…‘‘¥¹œ¡Á…±Á…±Á…±Á…¤íÍÉ½±°¹…‘‘Y¥•Ü¡°¤í1¥¹•…É1…å½ÕÐÉ½½Ðõ°ì(€€€€€€€Ñ•áÐ¡°°‰!™ÁY½¥Á1…ˆ€Ä¸Ü¸àˆ°ÈÜ¤íÑ•áÐ¡°°‰ÈË¥•ÁÑ¥½¸Ù…±¥“¥”ƒ
ÜÌ•ÍÍ…¤µ¥É¼ƒ
ÜÕ¸É…ÁÁ½ÉÐˆ°ÄØ¤ì(€€€€€€€ÍÑ…ÑÕÌõ¹•ÜQ•áÑY¥•Ü¡Ñ¡¥Ì¤íÍÑ…ÑÕÌ¹Í•ÑQ•áÑM¥é” ÄÔ¤í°¹…‘‘Y¥•Ü¡ÍÑ…ÑÕÌ¤ì(€€€€€€€¹½Ñ¥”õ¹•ÜQ•áÑY¥•Ü¡Ñ¡¥Ì¤í¹½Ñ¥”¹Í•ÑQ•áÑM¥é” ÄÔ¤í°¹…‘‘Y¥•Ü¡¹½Ñ¥”¤ì(€€€€€€€ÁÉ½‰•	ÕÑÑ½¸õ‰ÕÑÑ½¸¡°°‰[¥É¥™¥•ÈÉ½½Ð•Ðµ½‘Õ±”	±Õ•Ñ½½Ñ ˆ° ¤´ùÑ…Í¬  ¤´ùíMÑÉ¥¹œÀõ1…‰AÉ½‰”¹É•…¡Ñ¡¥Ì¤íÉ•ÅÕ•ÍÑ•õI½½Ð¹½µµ…¹ ‰•ÑÁÉ½À€ˆ­1…‰5½‘•Ì¹AI=@°ÄÀÀÀ°Ð¤¹ÑÉ¥´ ¤íÕ¤¹Á½ÍÐ  ¤´ùÑ½…ÍÐ ‰K¥Á½¹Í”Ë¥•¹Ñ”É—Õ”‘ÔÁÉ½•ÍÍÕÌ	±Õ•Ñ½½Ñ ¸ˆ¤¤íô¤¤ì(€€€€€€€Ñ•áÐ¡°°‰ÁÁ•±Ì‘ÔM…µÍÕ¹œ°Á¥±½Ó¥Ì‘•ÁÕ¥Ì±”I•‘µ¤ˆ°ÈÄ¤ì(€€€€€€€Á¡½¹•9Õµ‰•Èõ¹•Ü‘¥ÑQ•áÐ¡Ñ¡¥Ì¤íÁ¡½¹•9Õµ‰•È¹Í•Ñ!¥¹Ð ‰9Õ·¥É¼ƒ€…ÁÁ•±•ÈÍÕÈ±”M…µÍÕ¹œˆ¤íÁ¡½¹•9Õµ‰•È¹Í•Ñ%¹ÁÕÑQåÁ”¡…¹‘É½¥¹Ñ•áÐ¹%¹ÁÕÑQåÁ”¹QeA}1MM}A!=9¤íÁ¡½¹•9Õµ‰•È¹Í•ÑQ•áÐ ˆØØØˆ¤í°¹…‘‘Y¥•Ü¡Á¡½¹•9Õµ‰•È¤ì(€€€€€€€‰ÕÑÑ½¸¡°°‰ÁÁ•±•È‘•ÁÕ¥Ì±”I•‘µ¤ˆ° ¤´ù½¹ÑÉ½±…±° ‰‘¥…°ˆ¤¤ì(€€€€€€€‰ÕÑÑ½¸¡°°‰K¥Á½¹‘É”ƒ€³Še…ÁÁ•°‘ÔM…µÍÕ¹œˆ° ¤´ù½¹ÑÉ½±…±° ‰…¹ÍÝ•Èˆ¤¤ì(€€€€€€€‰ÕÑÑ½¸¡°°‰I…É½¡•È³Še…ÁÁ•°‘ÔM…µÍÕ¹œˆ° ¤´ù½¹ÑÉ½±…±° ‰¡…¹ÕÀˆ¤¤ì(€€€€€€€Ñ•áÐ¡°°‰1•Ì‰½ÕÑ½¹ÌÁ¥±½Ñ•¹Ð±”M…µÍÕ¹œÙ¥„!@¸1”µ½‘”€À±…¥ÍÍ”³Še…ÁÁ±¥…Ñ¥½¸S¥³¥Á¡½¹”¹‘É½¥Ÿ¥É•È³Še…ÁÁ•°€ìÈ½ÌÕÑ¥±¥Í•¹Ð±”Á½¹Ð‘”Ñ•ÍÐ¸ˆ°ÄÐ¤ì(€€€€€€€Ñ•áÐ¡°°‰¡½¥Í¥ÈÕ¸Á…É½ÕÉÌˆ°ÈÄ¤ì(€€€€€€€µ½‘•Ìõ¹•ÜMÁ¥¹¹•È¡Ñ¡¥Ì¤íµ½‘•Ì¹Í•Ñ‘…ÁÑ•È¡¹•ÜÉÉ…å‘…ÁÑ•Èðø¡Ñ¡¥Ì±…¹‘É½¥¹H¹±…å½ÕÐ¹Í¥µÁ±•}ÍÁ¥¹¹•É}‘É½Á‘½Ý¹}¥Ñ•´±AI%5Ie}95L¤¤íµ½‘•Ì¹Í•ÑM•±•Ñ¥½¸ Ä¤í°¹…‘‘Y¥•Ü¡µ½‘•Ì¤ì(€€€€€€€‘•Ñ…¥±Ìõ¹•ÜQ•áÑY¥•Ü¡Ñ¡¥Ì¤í‘•Ñ…¥±Ì¹Í•ÑQ•áÑM¥é” ÄØ¤í°¹…‘‘Y¥•Ü¡‘•Ñ…¥±Ì¤ì(€€€€€€€µ½‘•Ì¹Í•Ñ=¹%Ñ•µM•±•Ñ•‘1¥ÍÑ•¹•È¡¹•Ü…¹‘É½¥¹Ý¥‘•Ð¹‘…ÁÑ•ÉY¥•Ü¹=¹%Ñ•µM•±•Ñ•‘1¥ÍÑ•¹•È ¥íÁÕ‰±¥ŒÙ½¥½¹9½Ñ¡¥¹M•±•Ñ•¡…¹‘É½¥¹Ý¥‘•Ð¹‘…ÁÑ•ÉY¥•ÜðüøÀ¥íõÁÕ‰±¥ŒÙ½¥½¹%Ñ•µM•±•Ñ•¡…¹‘É½¥¹Ý¥‘•Ð¹‘…ÁÑ•ÉY¥•ÜðüøÀ±…¹‘É½¥¹Ù¥•Ü¹Y¥•ÜØ±¥¹Ð¤±±½¹œ¥¥í¥˜¡…‘Ù…¹•‘5½‘•Ì„õ¹Õ±°˜™…‘Ù…¹•‘5½‘•Ì¹•ÑM•±•Ñ•‘%Ñ•µA½Í¥Ñ¥½¸ ¤„ôÀ¥…‘Ù…¹•‘5½‘•Ì¹Í•ÑM•±•Ñ¥½¸ À¤íÍ¡½Ý5½‘” ¤íõô¤ì(€€€€€€€É¥Í¬õ¹•Ü¡•­	½à¡Ñ¡¥Ì¤íÉ¥Í¬¹Í•ÑQ•áÐ ‰ÕÑ½É¥Í•È±•ÌÍÑÉ…Ó¥¥•Ì•áÃ¥É¥µ•¹Ñ…±•ÌÁ½ÕÈ•ÑÑ”½ÕÙ•ÉÑÕÉ”ˆ¤íÉ¥Í¬¹Í•Ñ¡•­•¡™…±Í”¤íÉ¥Í¬¹Í•Ñ=¹¡•­•‘¡…¹•1¥ÍÑ•¹•È ¡ˆÄ±à¤´ùÉ•™É•Í  ¤¤í°¹…‘‘Y¥•Ü¡É¥Í¬¤ì(€€€€€€€…ÁÁ±äõ‰ÕÑÑ½¸¡°°‰ÁÁ±¥ÅÕ•È…ÔÁÉ½¡…¥¸…ÁÁ•°ˆ±Ñ¡¥Ìèé…ÁÁ±å5½‘”¤ì(€€€€€€€Ñ•áÐ¡°°‰A…É½ÕÉÌ€è¡½¥Í¥ÈÈ€£¥½ÕÑ•ÈÍÕÈ±”I•‘µ¤¤½ÔÌ€¡•¹Ù½å•È±”µ¥É¼‘ÔI•‘µ¤…Ô½ÉÉ•ÍÁ½¹‘…¹Ð¤°…ÁÁ±¥ÅÕ•È¡½ÉÌ…ÁÁ•°°“¥µ…ÉÉ•È±„…ÁÑÕÉ”°ÁÕ¥Ì…Éµ•È…Ù…¹Ð“Še…ÁÁ•±•È¸Ì•ÍÐÕ¸•ÍÍ…¤Q`Í•Õ°€è¥°»Še•¹É•¥ÍÑÉ”É¥•¸•Ð±„¹½Ñ¥™¥…Ñ¥½¸Á•Éµ•Ð³Še…ÉË©Ð¥µ·¥‘¥…Ð¸1”½ÉÉ•ÍÁ½¹‘…¹Ð‘½¥Ð½¹™¥Éµ•È±”µ¥É¼¸1”É½ÕÑ…”¹…Ñ¥˜¹‘É½¥É•ÍÑ”¥¹¡…¹Ÿ¤¡½ÉÌ…ÁÁ•°¸ˆ°ÄÔ¤ì(€€€€€€€Ñ•áÐ¡°°‰A½¹Ð…Õ‘¥¼ƒ
ÜÕ¹”‘¥É•Ñ¥½¸Á…È…ÁÁ•°ˆ°ÈÄ¤ì(€€€€€€€ÉáMÑ…ÑÕÌõ¹•ÜQ•áÑY¥•Ü¡Ñ¡¥Ì¤í°¹…‘‘Y¥•Ü¡ÉáMÑ…ÑÕÌ¤ì(€€€€€€€ÉáÉ´õ‰ÕÑÑ½¸¡°°‰Éµ•È±”µ½‘”¡½¥Í¤Á½ÕÈ±”ÁÉ½¡…¥¸…ÁÁ•°ˆ° ¤´ùì(€€€€€€€€€€€¥˜ …1…‰5½‘•Ì¹Í½™ÑÝ…É•	É¥‘”¡Í•±•Ñ•‘5½‘” ¤¤¥íÑ½…ÍÐ ‰3Še…Éµ•µ•¹Ð…Õ‘¥¼Í•ÉÐÍ•Õ±•µ•¹Ð…Õàµ½‘•ÌÈ•ÐÌ¸ˆ¤íÉ•ÑÕÉ¸íô(€€€€€€€€€€€¥˜¡¡•­M•±™A•Éµ¥ÍÍ¥½¸¡…¹‘É½¥¹5…¹¥™•ÍÐ¹Á•Éµ¥ÍÍ¥½¸¹I=I}U%<¤„õ…¹‘É½¥¹½¹Ñ•¹Ð¹Á´¹A…­…•5…¹…•È¹AI5%MM%=9}I9Q¥íÉ•ÅÕ•ÍÑA•Éµ¥ÍÍ¥½¹Ì¡¹•ÜMÑÉ¥¹muí…¹‘É½¥¹5…¹¥™•ÍÐ¹Á•Éµ¥ÍÍ¥½¸¹I=I}U%=ô°ÄØÀ¤íÑ½…ÍÐ ‰ÕÑ½É¥Í•È±„Á•Éµ¥ÍÍ¥½¸µ¥É½Á¡½¹”ÁÕ¥Ì…ÁÁÕå•È‘”¹½ÕÙ•…ÔÍÕÈÉµ•È¸ˆ¤íÉ•ÑÕÉ¸íô(€€€€€€€€€€€¥˜ …É¥Í¬¹¥Í¡•­• ¤¥íÑ½…ÍÐ ‰½¡•È³Še…ÕÑ½É¥Í…Ñ¥½¸‘•ÌÍÑÉ…Ó¥¥•Ì•áÃ¥É¥µ•¹Ñ…±•Ì¸ˆ¤íÉ•ÑÕÉ¸íô(€€€€€€€€€€€ÍÑ…ÉÑ½É•É½Õ¹‘M•ÉÙ¥”¡¹•Ü%¹Ñ•¹Ð¡Ñ¡¥Ì±Iá	É¥‘•M•ÉÙ¥”¹±…ÍÌ¤¹ÁÕÑáÑÉ„ ‰µ½‘”ˆ±Í•±•Ñ•‘5½‘” ¤¤¤ì(€€€€€€€ô¤ì(€€€€€€€ÉáMÑ½Àõ‰ÕÑÑ½¸¡°°‰ÉË©Ñ•È¥µ·¥‘¥…Ñ•µ•¹Ð±”Á½¹Ðˆ° ¤´ùÍÑ…ÉÑM•ÉÙ¥”¡¹•Ü%¹Ñ•¹Ð¡Ñ¡¥Ì±Iá	É¥‘•M•ÉÙ¥”¹±…ÍÌ¤¹Í•ÑÑ¥½¸ ‰ÍÑ½Àˆ¤¤¤ì(€€€€€€€1¥¹•…É1…å½ÕÐ…‘Ù…¹•õ¹•Ü1¥¹•…É1…å½ÕÐ¡Ñ¡¥Ì¤í…‘Ù…¹•¹Í•Ñ=É¥•¹Ñ…Ñ¥½¸ Ä¤í…‘Ù…¹•¹Í•ÑY¥Í¥‰¥±¥Ñä¡…¹‘É½¥¹Ù¥•Ü¹Y¥•Ü¹=9¤ì(€€€€€€€‰ÕÑÑ½¸¡É½½Ð°‰=ÕÑ¥±Ì…Ù…¹¥Ìƒ
Ü!$°™¥ÉµÝ…É”•Ð…ÕÑÉ•Ìµ½‘•Ìˆ° ¤´ù…‘Ù…¹•¹Í•ÑY¥Í¥‰¥±¥Ñä¡…‘Ù…¹•¹•ÑY¥Í¥‰¥±¥Ñä ¤ôõ…¹‘É½¥¹Ù¥•Ü¹Y¥•Ü¹Y%M%	1ý…¹‘É½¥¹Ù¥•Ü¹Y¥•Ü¹=9é…¹‘É½¥¹Ù¥•Ü¹Y¥•Ü¹Y%M%	1¤¤ì(€€€€€€€É½½Ð¹…‘‘Y¥•Ü¡…‘Ù…¹•¤ì(€€€€€€€°õ…‘Ù…¹•ì(€€€€€€€Ñ•áÐ¡°°‰5½‘”•áÃ¥É¥µ•¹Ñ…°ÍÕÁÁ³¥µ•¹Ñ…¥É”ˆ°ÈÄ¤ì(€€€€€€€©…Ù„¹ÕÑ¥°¹ÉÉ…å1¥ÍÐñMÑÉ¥¹œø…‘Ù…¹•‘9…µ•Ìõ¹•Ü©…Ù„¹ÕÑ¥°¹ÉÉ…å1¥ÍÐðø ¤í…‘Ù…¹•‘9…µ•Ì¹…‘ ‰ÕÕ¸ƒ
Ü…É‘•È±”Á…É½ÕÉÌÁÉ¥¹¥Á…°ˆ¤í™½È¡¥¹Ð¤ôÄí¤ñY9}%L¹±•¹Ñ í¤¬¬¥…‘Ù…¹•‘9…µ•Ì¹…‘¡1…‰5½‘•Ì¹95Mm1…‰5½‘•Ì¹¥¹‘•à¡Y9}%Mm¥t¥t¤ì(€€€€€€€…‘Ù…¹•‘5½‘•Ìõ¹•ÜMÁ¥¹¹•È¡Ñ¡¥Ì¤í…‘Ù…¹•‘5½‘•Ì¹Í•Ñ‘…ÁÑ•È¡¹•ÜÉÉ…å‘…ÁÑ•Èðø¡Ñ¡¥Ì±…¹‘É½¥¹H¹±…å½ÕÐ¹Í¥µÁ±•}ÍÁ¥¹¹•É}‘É½Á‘½Ý¹}¥Ñ•´±…‘Ù…¹•‘9…µ•Ì¤¤í…‘Ù…¹•‘5½‘•Ì¹Í•ÑM•±•Ñ¥½¸ À¤í°¹…‘‘Y¥•Ü¡…‘Ù…¹•‘5½‘•Ì¤ì(€€€€€€€…‘Ù…¹•‘5½‘•Ì¹Í•Ñ=¹%Ñ•µM•±•Ñ•‘1¥ÍÑ•¹•È¡¹•Ü…¹‘É½¥¹Ý¥‘•Ð¹‘…ÁÑ•ÉY¥•Ü¹=¹%Ñ•µM•±•Ñ•‘1¥ÍÑ•¹•È ¥íÁÕ‰±¥ŒÙ½¥½¹9½Ñ¡¥¹M•±•Ñ•¡…¹‘É½¥¹Ý¥‘•Ð¹‘…ÁÑ•ÉY¥•ÜðüøÀ¥íõÁÕ‰±¥ŒÙ½¥½¹%Ñ•µM•±•Ñ•¡…¹‘É½¥¹Ý¥‘•Ð¹‘…ÁÑ•ÉY¥•ÜðüøÀ±…¹‘É½¥¹Ù¥•Ü¹Y¥•ÜØ±¥¹Ð¤±±½¹œ¥¥íÍ¡½Ý5½‘” ¤íõô¤ì(€€€€€€€Ñ•áÐ¡°°‰QÉ…¹ÍÁ½ÉÐM<ƒ
Ü‘¥…¹½ÍÑ¥Œ¹…Ñ¥˜ˆ°ÈÄ¤ì(€€€€€€€ÑÉ…¹ÍÁ½ÉÑMÑ…ÑÕÌõ¹•ÜQ•áÑY¥•Ü¡Ñ¡¥Ì¤í°¹…‘‘Y¥•Ü¡ÑÉ…¹ÍÁ½ÉÑMÑ…ÑÕÌ¤ì(€€€€€€€Ñ•áÐ¡°°‰5½‘Õ±”	±Õ•Ñ½½Ñ …ÑÑ•¹‘Ô€è€Ä¸Ü¸à¸È½Ì¹”ÏŠe½ÕÙÉ•¹ÐÅ×Še…ÁË¡Ì½¹™¥Éµ…Ñ¥½¸‘Ôµ½‘”°‘ÔM<•Ð‘ÔÉ½ÕÑ…”Ë¥•°¸A½ÕÈÌ°Á…É±•È¹½Éµ…±•µ•¹ÐÁ•¹‘…¹Ð³Še…ÁÁ•°•Ð‘•µ…¹‘•È…Ô½ÉÉ•ÍÁ½¹‘…¹ÐÍ¤±„Ù½¥à•ÍÐ±…¥É”¸ÉË©Ñ•È±”Á½¹Ð½ÔÉ…É½¡•ÈÁ½ÕÈ½ÕÁ•È³Še…¡Ìµ¥É¼¸U¹”¹½ÕÙ•±±”ÑÉ…”!$»Še•ÍÐÁ…Ì»¥•ÍÍ…¥É”¸ˆ°ÄÔ¤ì(€€€€€€€‰ÕÑÑ½¸¡°°ˆÄƒ
ÜAË¥Á…É•È±„ÑÉ…”!$ˆ° ¤´ù¹•Ü±•ÉÑ¥…±½œ¹	Õ¥±‘•È¡Ñ¡¥Ì¤¹Í•ÑQ¥Ñ±” ‰Ñ¥Ù•ÈÑ•µÁ½É…¥É•µ•¹Ð±„ÑÉ…”	±Õ•Ñ½½Ñ €üˆ¤(€€€€€€€€€€€€¹Í•Ñ5•ÍÍ…” ‰¹‘É½¥Á½ÕÉÉ„ÍÑ½­•ÈÕ¸©½ÕÉ¹…°	±Õ•Ñ½½Ñ ‰ÉÕÐÍ•¹Í¥‰±”ÍÕÈ±”Ó¥³¥Á¡½¹”Á•¹‘…¹Ð•Ð•ÍÍ…¤¸1”±…ˆ¹”Á…ÉÑ…”ÅÕ”‘•Ì·¥Ñ…‘½¹»¥•ÌÑ•¡¹¥ÅÕ•Ì€èÁ…Ì‘”½¹Ñ•¹Ô0°¹Õ·¥É¼°…‘É•ÍÍ”°³¤½ÔÍ½¸¸1”Ë¥±…”ÁË¥¥‘•¹ÐÍ•É„Í…ÕÙ•…É“¤¸¥Í…Ñ¥Ù•È½Ë¥…Ñ¥Ù•È	±Õ•Ñ½½Ñ ¡½ÉÌ…ÁÁ•°•¹ÍÕ¥Ñ”€ì±”±…ˆ¹”ÍÕÁÁÉ¥µ”…ÕÕ¸…ÁÁ…É•¥°…ÁÁ…¥Ë¤¸5%U$Á•ÕÐ¥¹½É•È”Ë¥±…”=M@¸ˆ¤(€€€€€€€€€€€€¹Í•Ñ9•…Ñ¥Ù•	ÕÑÑ½¸ ‰¹¹Õ±•Èˆ±¹Õ±°¤¹Í•ÑA½Í¥Ñ¥Ù•	ÕÑÑ½¸ ‰AË¥Á…É•Èˆ°¡±Ü¤´ùÑ…Í¬  ¤´ùíQÉ…¹ÍÁ½ÉÑ¥…¹½ÍÑ¥Œ¹Í•Ñ1½¥¹œ¡Ñ¡¥Ì±ÑÉÕ”¤íÕ¤¹Á½ÍÐ  ¤´ùÑ½…ÍÐ ‰QÉ…”‘•µ…¹“¥”¸¥Í…Ñ¥Ù•ÈÁÕ¥ÌË¥…Ñ¥Ù•È	±Õ•Ñ½½Ñ ‘…¹ÌÍ•ÌË¥±…•Ì°…ÑÑ•¹‘É”±„É•½¹¹•á¥½¸‘ÔM…µÍÕ¹œ°ÁÕ¥Ì•™™•ÑÕ•Èƒn4ÚÚ$z{-®éÜj×iser explicitement les stratÃ©gies expÃ©rimentales.");return;}
        task(()->{
            String probe=LabProbe.read(this);
            if(!probe.contains("version=1.7.8 "))throw new IOException("Ancien module encore chargÃ© : redÃ©marrer une fois pour charger 1.7.8.");
            if(!probe.contains(" busy=false "))throw new IOException("Appel ou SCO actif : attendre le raccrochage complet.");
            if(!choice.equals("observe")&&probe.contains(" dirty=true "))throw new IOException("Nettoyage audio incomplet : exporter et arrÃªter les essais.");
            if(!choice.equals("observe")&&(!probe.contains(" route=true ")||!probe.contains(" calls=true ")))throw new IOException("Hooks de suivi indisponibles : seule Observation est autorisÃ©e.");
            if(LabModes.bypass(choice)&&!probe.contains(" bypass=true "))throw new IOException("Mode D indisponible sur ce processus.");
            if((choice.equals("bypass_comm")||LabModes.softwareBridge(choice))&&!probe.contains(" disconnect=true "))throw new IOException("D1 indisponible : hook de dÃ©connexion manquant.");
            if(LabModes.voip(choice)&&!probe.contains(" voip=3 "))throw new IOException("Hooks VoIP incomplets.");
            String answer=Root.command("setprop "+LabModes.PROP+" "+choice+" && getprop "+LabModes.PROP,1000,5).trim();
            if(!choice.equals(answer))throw new IOException("Mode non confirmÃ© par getprop");
            requested=choice;
            String phase=prefs().getString("phase","idle");if(phase.equals("running"))SessionStore.note(this,"Mode demandÃ© : "+choice);
            LabProbe.read(this);
            ui.post(()->toast("Mode demandÃ© : "+choice+". Les logs du prochain appel confirmeront les opÃ©rations appliquÃ©es."));
        });
    }
    private void rating(){try{
        String[] calls=SessionStore.ended(this);if(calls.length==0){toast("Aucun appel terminÃ© dÃ©tectÃ© dans cette capture. Ne pas attribuer de rÃ©sultat Ã  un appel non identifiÃ©.");return;}
        LinearLayout l=new LinearLayout(this);l.setOrientation(1);l.setPadding(25,10,25,10);
        text(l,"Appel terminÃ©",16);Spinner call=new Spinner(this);call.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,calls));call.setSelection(calls.length-1);l.addView(call);
        text(l,"RÃ©ception sur le Redmi",16);Spinner rx=new Spinner(this);rx.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,RESULTS));l.addView(rx);
        text(l,"Microphone : ce quâ€™entend le correspondant",16);Spinner tx=new Spinner(this);tx.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,RESULTS));l.addView(tx);
        EditText other=new EditText(this);other.setHint("Commentaire facultatif (sans numÃ©ro ni nom)");l.addView(other);
        new AlertDialog.Builder(this).setTitle("Observation auditive").setView(l).setNegativeButton("Annuler",null).setPositiveButton("Enregistrer",(d,w)->{
            try{String key=calls[call.getSelectedItemPosition()].split(" Â· ")[0];SessionStore.result(this,key,RESULTS[rx.getSelectedItemPosition()],RESULTS[tx.getSelectedItemPosition()],other.getText().toString());toast("RÃ©sultat enregistrÃ© pour "+key);}catch(Exception e){toast("Erreur : "+e.getMessage());}
        }).show();
    }catch(Exception e){toast("Erreur : "+e.getMessage());}}
    private void inspectReport(){String[] names={"summary.txt","sessions.json","errors.txt","hfp-events.log","audio-policy.txt","audio-flinger.txt","mediatek-audio.log","system-info.txt","audio-config.txt","audio-manager.txt"};
        inspectZip("HFP-Rapport.zip",names);
    }
    private void inspectZip(String archive,String[] names){
        new AlertDialog.Builder(this).setTitle("VÃ©rifier le ZIP").setItems(names,(d,w)->task(()->{
            StringBuilder content=new StringBuilder();boolean cut=false;
            try(java.util.zip.ZipFile zip=new java.util.zip.ZipFile(new File(getFilesDir(),archive))){
                java.util.zip.ZipEntry entry=zip.getEntry(names[w]);if(entry==null)throw new IOException("Fichier absent");
                try(BufferedReader in=new BufferedReader(new InputStreamReader(zip.getInputStream(entry),StandardCharsets.UTF_8))){String line;
                    while((line=in.readLine())!=null){if(content.length()>120000){cut=true;break;}content.append(line).append('\n');}
                }
            }
            final String shown=content.toString()+(cut?"\nAPERÃ‡U LIMITÃ‰ : ouvrir le ZIP pour consulter la totalitÃ©.":"");
            ui.post(()->{ScrollView sc=new ScrollView(this);TextView t=new TextView(this);t.setText(shown);t.setTextSize(12);t.setTextIsSelectable(true);sc.addView(t);
                new AlertDialog.Builder(this).setTitle(names[w]).setView(sc).setPositiveButton("Fermer",null).show();});
        })).setNegativeButton("Fermer",null).show();
    }
    private void refresh(){if(status==null)return;
        String phase=prefs().getString("phase","idle"),p=prefs().getString("probe","");long at=prefs().getLong("probe_at",0);
        if((phase.equals("running")||phase.equals("starting")||phase.equals("processing"))&&!CaptureService.alive){
            phase="error";prefs().edit().putString("phase","error").putString("status","Service interrompu. Terminer pour rÃ©cupÃ©rer les fichiers conservÃ©s.").apply();
        }
        boolean fresh=System.currentTimeMillis()-at<15000;
        String module=p.isEmpty()?"non confirmÃ©":(fresh?"rÃ©ponse rÃ©cente":"derniÃ¨re rÃ©ponse il y a "+((System.currentTimeMillis()-at)/1000)+" s");
        String applied="non confirmÃ©";java.util.regex.Matcher m=java.util.regex.Pattern.compile("applied=(\\w+)").matcher(p);if(m.find())applied=m.group(1).equals("idle")?"aucun appel (derniÃ¨re vÃ©rification)":m.group(1)+" (derniÃ¨re vÃ©rification)";
        status.setText("Root Magisk : "+prefs().getString("root","non vÃ©rifiÃ©")+"\nModule LSPosed / Bluetooth : "+module+
            "\nMode demandÃ© : "+requested+"\nStratÃ©gie retenue : "+applied+"\nDernier appel capturÃ© : "+prefs().getString("last_mode","aucun")+" Â· Ã©tat HFP "+prefs().getString("last_call_state","â€”")+"\nCapture : "+prefs().getString("status","inactive")+
            "\nApplication technique : "+prefs().getString("strategy","non vÃ©rifiÃ©e")+"\nÃ‰vÃ©nements Ã©crits : "+prefs().getLong("count",0)+"\nDerniÃ¨re anomalie : "+prefs().getString("error","aucune"));
        android.content.SharedPreferences fp=getSharedPreferences("firmware",0);
        String fs=fp.getString("phase","idle");
        if(fs.equals("running")&&!FirmwareService.alive){fs="error";fp.edit().putString("phase",fs).putString("status","Collecte interrompue : relancer hors appel.").apply();}
        boolean collecting=FirmwareService.alive;
        if(transportStatus!=null)transportStatus.setText(getSharedPreferences("transport",0).contains("previous")?"Trace demandÃ©e par le lab : rÃ©glage prÃ©cÃ©dent sauvegardÃ©, Ã  restaurer aprÃ¨s collecte. Activation rÃ©elle Ã  confirmer dans hci-transport.txt.":"Aucun rÃ©glage de trace dÃ©tenu par le lab. Le rÃ©glage systÃ¨me peut Ãªtre diffÃ©rent.");
        boolean bridging=RxBridgeService.alive;
        if(rxStatus!=null)rxStatus.setText(getSharedPreferences("rx",0).getString("status","Pont non armÃ©."));
        if(rxArm!=null){rxArm.setEnabled(!bridging&&!collecting&&!working&&phase.equals("running")&&risk.isChecked()&&LabModes.softwareBridge(selectedMode()));rxStop.setEnabled(bridging);}
        if(probeButton!=null)probeButton.setEnabled(!bridging&&!working);
        if(firmwareStatus!=null)firmwareStatus.setText(fp.getString("status","Aucune collecte statique effectuÃ©e."));
        if(firmware!=null){firmware.setEnabled(!bridging&&!CaptureService.alive&&!collecting&&!working);boolean fr=fs.equals("ready")&&!collecting&&new File(getFilesDir(),"HFP-Firmware.zip").isFile();firmwareShare.setEnabled(fr);firmwareInspect.setEnabled(fr&&!working);}
        boolean running=phase.equals("running"), starting=phase.equals("starting"), processing=phase.equals("processing");
        if(start!=null){start.setEnabled(!collecting&&!running&&!starting&&!processing&&!working);stop.setEnabled(!bridging&&(running||starting||phase.equals("error"))&&!processing);snap.setEnabled(running);rate.setEnabled(running);}
        if(apply!=null)apply.setEnabled(!bridging&&!collecting&&!working&&!starting&&!processing&&(!LabModes.risky(selectedMode())||risk.isChecked()));
        boolean ready=phase.equals("ready")&&new File(getFilesDir(),"HFP-Rapport.zip").isFile();if(share!=null){share.setEnabled(ready);inspect.setEnabled(ready&&!working);}
    }
    private final Runnable poll=new Runnable(){public void run(){refresh();if(visible)ui.postDelayed(this,1000);}};
    @Override protected void onResume(){super.onResume();visible=true;poll.run();}
    @Override protected void onPause(){visible=false;ui.removeCallbacks(poll);super.onPause();}
    @Override protected void onDestroy(){work.shutdown();super.onDestroy();}
}
